export const FUND_LIST_REQUEST = 'FUND_LIST_REQUEST';
export const FUND_LIST_SUCCESS = 'FUND_LIST_SUCCESS';
export const FUND_LIST_FAIL = 'FUND_LIST_FAIL';

export const FUND_DETAILS_REQUEST = "FUND_DETAILS_REQUEST";
export const FUND_DETAILS_SUCCESS = "FUND_DETAILS_SUCCESS";
export const FUND_DETAILS_FAIL = "FUND_DETAILS_FAIL";

export const FUND_SEARCH_REQUEST = "FUND_SEARCH_REQUEST";
export const FUND_SEARCH_SUCCESS = "FUND_SEARCH_SUCCESS";
export const FUND_SEARCH_FAIL = "FUND_SEARCH_FAIL";